Web/ViewModels/Employee/EmployeeEditViewModel.cs
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using Microsoft.AspNetCore.Identity.EntityFrameworkCore;
using WebApp.Entities;
using WebApp.Models;

namespace WebApp.ViewModels
{
    public class EmployeeEditViewModel
    {
        public string EditId { get; set; }


        [UIHint("string")]
        [Display(Name = "Ф.И.О.")]
        public string FIO { get; set; }

        [Editable(false)]
        [UIHint("string")]
        [Display(Name = "Email")]
        public string Email { get; set; }

        [UIHint("string")]
        [Display(Name = "Пароль")]
        public string OpenPassword { get; set; }

        [UIHint("checkbox")]
        [Display(Name = "Создание объектов")]
        public bool IsCreateHousing { get; set; }

        [UIHint("checkbox")]
        [Display(Name = "Редактирование объектов")]
        public bool IsEditHousing { get; set; }

        [UIHint("checkbox")]
        [Display(Name = "Удаление объектов")]
        public bool IsDeleteHousiong { get; set; }

        [UIHint("checkbox")]
        [Display(Name = "Создание карточки клиентов")]
        public bool IsCreateCustomer { get; set; }

        [UIHint("checkbox")]
        [Display(Name = "Редактирование карточки клиентов")]
        public bool IsEditCustomer { get; set; }

        [UIHint("checkbox")]
        [Display(Name = "Удаление карточки клиентов")]
        public bool IsDeleteCustomer { get; set; }

        [UIHint("checkbox")]
        [Display(Name = "Создание и редактирование пользователей")]
        public bool IsManageUsers { get; set; }

        [UIHint("city-selector")]
        [Display(Name = "Город")]
        public int CityId { get; set; }

        public EmployeeEditViewModel()
        {
        }

        public EmployeeEditViewModel(int cityId)
        {
            CityId = cityId;
        }

        public List<string> GetSelectedRoles()
        {
            var roles = new List<string>();
            //customer
            if (IsCreateCustomer) { roles.Add(RoleNames.CreateCustomer); }
            if (IsEditCustomer) { roles.Add(RoleNames.EditCustomer); }
            if (IsDeleteCustomer) { roles.Add(RoleNames.DeleteCustomer); }

            //housing
            if (IsCreateHousing) { roles.Add(RoleNames.CreateHousing); }
            if (IsEditHousing) { roles.Add(RoleNames.EditHousing); }
            if (IsDeleteHousiong) { roles.Add(RoleNames.DeleteHousing); }

            //
            if (IsManageUsers) { roles.Add(RoleNames.ManageUser); }

            return roles;
        }


        public static EmployeeEditViewModel CreateForEdit(ApplicationUser user, List<IdentityRole> roles, List<City> cityList)
        {
            Dictionary<string, IdentityRole> roleMap = roles.ToDictionary(x => x.Id, x => x);
            var item = new EmployeeEditViewModel
            {
                EditId = user.Id,
                FIO = user.FIO,
                Email = user.Email,
                OpenPassword = user.OpenPassword,
                CityId = user.CityId ?? 0,
                IsCreateCustomer = user.Roles.SingleOrDefault(x => roleMap[x.RoleId].Name == RoleNames.CreateCustomer) != null,
                IsEditCustomer = user.Roles.SingleOrDefault(x => roleMap[x.RoleId].Name == RoleNames.EditCustomer) != null,
                IsDeleteCustomer = user.Roles.SingleOrDefault(x => roleMap[x.RoleId].Name == RoleNames.DeleteCustomer) != null,

                IsCreateHousing= user.Roles.SingleOrDefault(x => roleMap[x.RoleId].Name == RoleNames.CreateHousing) != null,
                IsEditHousing = user.Roles.SingleOrDefault(x => roleMap[x.RoleId].Name == RoleNames.EditHousing) != null,
                IsDeleteHousiong = user.Roles.SingleOrDefault(x => roleMap[x.RoleId].Name == RoleNames.DeleteHousing) != null,

                IsManageUsers = user.Roles.SingleOrDefault(x => roleMap[x.RoleId].Name == RoleNames.ManageUser) != null,
            };

            return item;
        }
    }
}

Web/ViewModels/Employee/EmployeeRegisterViewModel.cs
using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.ComponentModel.DataAnnotations;
using System.Threading.Tasks;
using WebApp.Entities;

namespace WebApp.ViewModels
{
    public class EmployeeRegisterViewModel : EmployeeEditViewModel
    {

        [UIHint("string")]
        [Required]
        [EmailAddress]
        [Display(Name = "Email")]
        public string Email { get; set; }

        [UIHint("string")]
        [Required]
        [StringLength(100, ErrorMessage = "The {0} must be at least {2} characters long.", MinimumLength = 6)]
        [DataType(DataType.Password)]
        [Display(Name = "Пароль")]
        public string Password { get; set; }

        [UIHint("string")]
        [DataType(DataType.Password)]
        [Display(Name = "Подтвердите пароль")]
        [Compare("Password", ErrorMessage = "Пароли не совпадают.")]
        public string ConfirmPassword { get; set; }

        public EmployeeRegisterViewModel(): base()
        {
        }

        public EmployeeRegisterViewModel(int cityId) : base(cityId)
        {
        }

    }
}

Web/Controllers/EmployeeController.cs
using System.Collections.Generic;
using System.Linq;
using System.Security.Claims;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using WebApp.Models;
using WebApp.ViewModels;
using WebApp.ViewModels.Account;

namespace WebApp.Controllers
{
    [Authorize(AuthPolicy.ManageUser)]
    public class EmployeeController : Controller
    {
        private ApplicationDbContext _context;
        private UserManager<ApplicationUser> _userManager;

        public EmployeeController(ApplicationDbContext context, UserManager<ApplicationUser> userManager)
        {
            _context = context;
            this._userManager = userManager;
        }

        [Authorize(AuthPolicy.ManageUser)]
        // GET: Employee
        public IActionResult Index()
        {
            var identityRoles = _context.Roles.ToList();
            var roleEmployee = _context.Roles.Single(x => x.Name == RoleNames.Employee);
            var model = _context.ApplicationUser.Include(x => x.Roles)
                .Where(x => x.Roles.Any(r => r.RoleId == roleEmployee.Id))
                .ToList()
                .Select(x => EmployeeEditViewModel.CreateForEdit(x, identityRoles, _context.Cities.ToList())).ToList();
            return View(model);
        }

        [Authorize]
        public IActionResult Create()
        {
            var model = new EmployeeRegisterViewModel(0);
            return View(model);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create(EmployeeRegisterViewModel model)
        {
            if (ModelState.IsValid)
            {
                var user = new ApplicationUser
                {
                    FIO = model.FIO,
                    UserName = model.Email,
                    Email = model.Email,
                    OpenPassword = model.Password
                };
                var result = await _userManager.CreateAsync(user, model.Password);
                if (result.Succeeded)
                {
                    var roles = new List<string>();
                    roles.Add(RoleNames.Employee);
                    roles.AddRange(model.GetSelectedRoles());
                    
                    var resultRole = await _userManager.AddToRolesAsync(user, roles);

                    return RedirectToAction(nameof(Index));
                }
                AddErrors(result);
            }
            
            return View(model);
        }

        private void AddErrors(IdentityResult result)
        {
            foreach (var error in result.Errors)
            {
                ModelState.AddModelError(string.Empty, error.Description);
            }
        }

        // GET: Employee/Details/5
        public IActionResult Details(string id)
        {
            if (id == null)
            {
                return NotFound();
            }

            ApplicationUser applicationUser = _context.ApplicationUser.Single(m => m.Id == id);
            if (applicationUser == null)
            {
                return NotFound();
            }

            return View(applicationUser);
        }
        
        // GET: Employee/Edit/5
        public IActionResult Edit(string id)
        {
            if (id == null)
            {
                return NotFound();
            }
            
            ApplicationUser applicationUser = _context.ApplicationUser.GetById(id);
            if (applicationUser == null)
            {
                return NotFound();
            }

            var roles = _context.Roles.ToList();
            var cityList = _context.Cities.ToList();
            return View(EmployeeEditViewModel.CreateForEdit(applicationUser, roles, cityList));
        }

        // POST: Employee/Edit/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(EmployeeEditViewModel model, string editId)
        {
            if (ModelState.IsValid)
            {
                ApplicationUser user = _context.ApplicationUser.GetById(editId);
                user.FIO = model.FIO;
                user.CityId = model.CityId;

                var selectedRoles = model.GetSelectedRoles();
                foreach (var roleName in RoleNames.PermissionRoles)
                {
                    bool isSelected = selectedRoles.Contains(roleName);
                    bool userInRole = await _userManager.IsInRoleAsync(user, roleName);
                    if (isSelected)
                    {
                        if (!userInRole)
                        {
                            await _userManager.AddToRoleAsync(user, roleName);
                        }
                    }
                    else
                    {
                        if (userInRole)
                        {
                            await _userManager.RemoveFromRoleAsync(user, roleName);
                        }
                    }
                }

                _context.Update(user);
                _context.SaveChanges();
                return RedirectToAction("Index");
            }
            return View();
        }

        // GET: Employee/Delete/5
        [ActionName("Delete")]
        public IActionResult Delete(string id)
        {
            if (id == null)
            {
                return NotFound();
            }

            ApplicationUser applicationUser = _context.ApplicationUser.Single(m => m.Id == id);
            if (applicationUser == null)
            {
                return NotFound();
            }

            _context.ApplicationUser.Remove(applicationUser);
            _context.SaveChanges();
            return RedirectToAction(nameof(Index));
        }
        
    }
}

Web/Views/Employee/Create.cshtml
@using System.Threading.Tasks
@using WebApp.ViewModels
@model WebApp.ViewModels.EmployeeRegisterViewModel
@{
    ViewData["Title"] = "Регистрация сотрудника";
}

<h2>@ViewData["Title"]</h2>

<form asp-controller="Employee" asp-action="Register" method="post" class="ui form" role="form">
    <h4>Создание новой карточки сотрудника</h4>
    <hr />
    <div asp-validation-summary="All" class="text-danger"></div>
    @Html.EditorFor(x => x.Email)
    @Html.EditorFor(x => x.Password)
    @Html.EditorFor(x => x.ConfirmPassword)

    @Html.EditorFor(x => x.FIO)

    @Html.EditorFor(x => x.CityId)

    @Html.EditorFor(x => x.IsCreateHousing)
    @Html.EditorFor(x => x.IsEditHousing)
    @Html.EditorFor(x => x.IsDeleteHousiong)
    @Html.EditorFor(x => x.IsCreateCustomer)
    @Html.EditorFor(x => x.IsEditCustomer)
    @Html.EditorFor(x => x.IsDeleteCustomer)
    @Html.EditorFor(x => x.IsManageUsers)


    <div class="ui buttons">
        <button type="submit" class="ui button blue">Создать карточку</button>
    </div>
    <a asp-action="Index" >Вернуться к списку</a>
    
</form>

Web/Views/Employee/Edit.cshtml
@using System.Threading.Tasks
@using WebApp.ViewModels
@model WebApp.ViewModels.EmployeeEditViewModel
@{
    ViewData["Title"] = "Редактирование";
}

<h2>@ViewData["Title"]</h2>

<form asp-controller="Employee" asp-action="Edit" method="post" class="ui form" role="form">
    <h4>Редактирование карточки сотрудника</h4>
    <hr />
    <div asp-validation-summary="All" class="text-danger"></div>
    @Html.HiddenFor(x => x.EditId)
    @Html.DisplayFor(x => x.Email, "string-field")
    @Html.EditorFor(x => x.FIO)
    @Html.EditorFor(x => x.CityId)

    @Html.EditorFor(x => x.IsCreateHousing)
    @Html.EditorFor(x => x.IsEditHousing)
    @Html.EditorFor(x => x.IsDeleteHousiong)
    @Html.EditorFor(x => x.IsCreateCustomer)
    @Html.EditorFor(x => x.IsEditCustomer)
    @Html.EditorFor(x => x.IsDeleteCustomer)
    @Html.EditorFor(x => x.IsManageUsers)


    <div class="ui buttons">
        <button type="submit" class="ui button blue">Сохранить изменения</button>
        <button asp-action="Delete" asp-route-id="@Model.EditId" onclick="return confirm('Вы уверены что хотите удалить запись?');" class="ui button red">Удалить</button>
    </div>
    <a asp-action="Index" >Вернуться к списку</a>
</form>

Web/Views/Employee/Index.cshtml
@model List<WebApp.ViewModels.EmployeeEditViewModel>

@{
    ViewData["Title"] = "Сотрудники";
}

<h2>Список сотрудников</h2>

<p>
    <a asp-action="Create" class="ui button blue">Добавить нового сотрудника</a>
</p>



@if (!Model.Any())
{
    <div class="ui negative message">
        <div class="header">
            Список сотрудников пуст
        </div>
        <p>Чтобы добавить нового сотрудника нажмите <a asp-action="Create">на ссылку</a>
        </p>
    </div>    
}
else
{
    <table class="ui collapsing selectable  table">
        <thead>
        <tr>
            <th class="two wide">@Html.DisplayNameFor(x => Model[0].FIO)</th>
            <th>@Html.DisplayNameFor(x => Model[0].Email)</th>
            <th>@Html.DisplayNameFor(x => Model[0].OpenPassword)</th>
              <th>@Html.DisplayNameFor(x => Model[0].CityId)</th>
            <th>@Html.DisplayNameFor(x => Model[0].IsCreateHousing)</th>
            <th>@Html.DisplayNameFor(x => Model[0].IsEditHousing)</th>
            <th>@Html.DisplayNameFor(x => Model[0].IsDeleteHousiong)</th>
            <th>@Html.DisplayNameFor(x => Model[0].IsCreateCustomer)</th>
            <th>@Html.DisplayNameFor(x => Model[0].IsEditCustomer)</th>
            <th>@Html.DisplayNameFor(x => Model[0].IsDeleteCustomer)</th>
            <th>@Html.DisplayNameFor(x => Model[0].IsManageUsers)</th>
            <th></th>
        </tr>
        </thead>
        <tbody>
        @foreach (var item in Model)
        {
            <tr>
                <td>@item.FIO</td>
                <td>@item.Email</td>
                <td>@item.OpenPassword</td>
                <td>@Html.DisplayFor(x => item.CityId)</td>
                <td>@Html.DisplayFor(x => item.IsCreateHousing, "bool-text")</td>
                <td>@Html.DisplayFor(x => item.IsEditHousing, "bool-text")</td>
                <td>@Html.DisplayFor(x => item.IsDeleteHousiong, "bool-text")</td>
                <td>@Html.DisplayFor(x => item.IsCreateCustomer, "bool-text")</td>
                <td>@Html.DisplayFor(x => item.IsEditCustomer, "bool-text")</td>
                <td>@Html.DisplayFor(x => item.IsDeleteCustomer, "bool-text")</td>
                <td>@Html.DisplayFor(x => item.IsManageUsers, "bool-text")</td>
                <td>
                    <div class="ui icon buttons">
                        <a asp-action="Edit" asp-route-id="@item.EditId" class="ui circular icon button basic  blue" title="Редактирование"><i class="edit icon"></i></a>

                        <a asp-action="Delete" asp-route-id="@item.EditId" class="ui button red tiny basic" onclick="return confirm('Вы уверены что хотите удалить запись?');" title="Удалить"><i class="trash icon"></i></a>
                    </div>
                </td>
            </tr>
        }

        </tbody>
    </table>
}