Web/Controllers/HousingController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Data;
using Data.Command;
using Data.Query;
using Data.Query.CitiesQuery;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using Web;
using Web.Helpers;
using WebApp.Data;
using WebApp.ViewModels;
using WebApp.Entities;
using WebApp.Models;

namespace WebApp.Controllers
{
    [Authorize(AuthPolicy.Employees)]
    public class HousingController: BaseController
    {
        private IAuthorizationService AuthService { get; set; }
        private ReadOnlyDataContext ReadOnlyDataContext { get; }
        private IQueryDispatcher QueryDispatcher { get; }
        private ICommandDispatcher CommandDispatcher { get; }
        
        private BuilderFactory BuilderFactory { get; }

        public HousingController(
            ApplicationDbContext context, 
            IAuthorizationService auth, 
            ReadOnlyDataContext readOnlyDataContext, 
            IQueryDispatcher queryDispatcher, 
            HousingEditModelBuilder housingEditModelBuilder, ICommandDispatcher commandDispatcher, BuilderFactory builderFactory) : base(context)
        {
            AuthService = auth;
            ReadOnlyDataContext = readOnlyDataContext;
            QueryDispatcher = queryDispatcher;
            CommandDispatcher = commandDispatcher;
            BuilderFactory = builderFactory;
        }

        public async Task<IActionResult> Index(string filter, 
            int page = 1, 
            int? houseType = null, 
            int? cityId = null, 
            int? districtId = null, 
            int? minCost = null, 
            int? maxCost = null, 
            int? objectId = null, 
            bool? isArchive = null)
        {
            if (User.IsInRole(RoleNames.Employee))
            {
                cityId = CurrentUser?.City?.Id;
            }

            var filterData = new HousingPagedQuery
            {
                PageSize = 20,
                PageNumber = page,
                CityId = cityId,
                PriceTo = minCost,
                PriceFrom = maxCost,
                Page = page,
                IsArchived = isArchive
            };

            if (houseType.HasValue)
            {
                filterData.HouseTypeId = new int[] { houseType.Value };
            }
            
            
            var query = await QueryDispatcher.ExecuteAsync<HousingPagedQuery, PagedResults<Housing>>(filterData);
            
            var items = query.Items.Select(x =>
            {
                return BuilderFactory.Create<HousingEditModelBuilder>().Build(x);
            }).ToList();

            ViewBag.TotalItems = await QueryDispatcher.ExecuteAsync<HousingCountQuery, int>(new HousingCountQuery());
            ViewBag.FilteredItemsCount = query.PageInfo.TotalItems;

            var model = new HousingIndexModel
            {
                Items = items,
                Filters = new HousingIndexFilterModel
                {
                    IsArchived = isArchive ?? false,
                    HousingTypeId = houseType ?? 0,
                    CityId = cityId ?? 0,
                    DistrictId = districtId ?? 0
                },
                PageInfo = query.PageInfo
            };
            
            return View(model);
        }


        public Task<IActionResult> Cards(string filter,
            int page = 1,
            int? houseType = null,
            int? cityId = null,
            int? districtId = null,
            int? minCost = null,
            int? maxCost = null,
            int? objectId = null,
            bool? isArchive = null)
        {
            return Index(filter, page, houseType, cityId, districtId, minCost, maxCost, objectId, isArchive);
        }

        [HttpPost]
        public IActionResult Filter(HousingIndexModel model, int page = 1)
        {
            var filters = model.Filters;
            if (filters == null)
            {
                return RedirectToAction("Index", new { page });
            }

            Func<int?, int?> intOrNull = (value) =>
            {
                if (value.HasValue && value.Value > 0)
                {
                    return value;
                }
                return null;
            };
            
            return RedirectToAction("Index", new
            {
                page,
                houseType = intOrNull(filters.HousingTypeId),
                cityId = intOrNull(filters.CityId),
                districtId = intOrNull(filters.DistrictId),
                minCost = intOrNull(filters.MinCost),
                maxCost = intOrNull(filters.MaxCost),
                objectId = intOrNull(filters.SelectedObjectId),
                isArchive = filters.IsArchived
            });
        }
        

        public IActionResult ResetFilter(int? page = 1)
        {
            return RedirectToAction("Index", new { page });
        }

        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            Housing housing = await QueryDispatcher.ExecuteAsync<HousingFullByIdQuery, Housing>(new HousingFullByIdQuery(id.Value));
            
            if (housing == null)
            {
                return NotFound();
            }
            var model = await BuilderFactory.Create<HousingEditModelBuilder>().BuildAsync(id.Value);
            return View(model);
        }
        
        [Authorize(AuthPolicy.CreateHousing)]
        public async Task<IActionResult> Create()
        {
            var city = User.IsInRole(RoleNames.Employee)
                ? CurrentUser?.City
                : (await QueryDispatcher.ExecuteAsync<CitiesAllQuery, List<City>>(new CitiesAllQuery())).FirstOrDefault();
                
            var housing = new Housing()
            {
                City = city,
                CityId = city?.Id ?? 0,
                Phones = new List<HousingPhone>(),
                Calls = new List<HousingCall>()
            };
            var model = BuilderFactory.Create<HousingEditModelBuilder>().Build(housing);
            return View("Save", model);
        }

        [HttpPost]
        [Authorize(AuthPolicy.CreateHousing)]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create(HousingEditModel housing)
        {
            if (ModelState.IsValid)
            {
                var newHousingItem = new Housing()
                {
                    Phones = new List<HousingPhone>()
                };
                housing.UpdateEntity(newHousingItem);

                await CommandDispatcher.ExecuteAsync(new AddHousingCommand(newHousingItem));
                SuccessMessage("Запись добавлена");
                
                return RedirectToAction("Index");
            }
            return View("Save", housing);
        }

        [Authorize(AuthPolicy.EditHousing)]
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            Housing housing = await QueryDispatcher.ExecuteAsync<HousingFullByIdQuery, Housing>(new HousingFullByIdQuery(id.Value));
                
            if (housing == null)
            {
                return NotFound();
            }

            var model = await BuilderFactory.Create<HousingEditModelBuilder>().BuildAsync(id.Value);
            return View("Save", model);
        }

        [HttpPost]
        [Authorize(AuthPolicy.EditHousing)]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(HousingEditModel housing, int editId)
        {
            if (ModelState.IsValid)
            {
                var dbItem = await QueryDispatcher.ExecuteAsync<HousingFullByIdQuery, Housing>(new HousingFullByIdQuery(editId));

                housing.UpdateEntity(dbItem);

                await CommandDispatcher.ExecuteAsync(new UpdateHousingCommand(dbItem));

                TempData["CrmSuccessMessage"] = "Запись была успешно сохранена";
                return RedirectToAction("Index");
            }

            var errors = ModelState.Values.Where(x => x.Errors.Any()).ToList();
            return View("Save", housing);
        }

        [Authorize(AuthPolicy.DeleteHousing)]
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            if (await QueryDispatcher.ExecuteAsync<HousingExistQuery, bool>(new HousingExistQuery(id)))
            {
                await CommandDispatcher.ExecuteAsync(new DeleteHousingCommand(id));
            }
            return RedirectToAction("Index");
        }

        [Authorize(AuthPolicy.EditHousing)]
        public async Task<IActionResult> ToArchive(int id)
        {
            Housing housing = await QueryDispatcher.ExecuteAsync<HousingFullByIdQuery, Housing>(new HousingFullByIdQuery(id));
            housing.IsArchive = true;
            await CommandDispatcher.ExecuteAsync(new UpdateHousingCommand(housing));
            SuccessMessage("Запись отправлена в архив");
            return RedirectToAction("Index");
        }

        [Authorize(AuthPolicy.EditHousing)]
        public async Task<IActionResult> FromArchive(int id)
        {
            Housing housing = await QueryDispatcher.ExecuteAsync<HousingFullByIdQuery, Housing>(new HousingFullByIdQuery(id));
            housing.IsArchive = false;

            await CommandDispatcher.ExecuteAsync(new UpdateHousingCommand(housing));
            SuccessMessage("Запись больше не в архиве");
            return RedirectToAction("Index");
        }


        [Authorize(AuthPolicy.EditHousing)]
        public async Task<JsonResult> AddCall(int housingId, string status)
        {

Web/Controllers/StreetsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;

using WebApp.Entities;
using WebApp.Models;
using Microsoft.AspNetCore.Authorization;
using Microsoft.EntityFrameworkCore;
using WebApp.Models.SemanticUI;
using WebApp.ViewModels;

namespace WebApp.Controllers
{
    [Authorize(AuthPolicy.Employees)]
    public class StreetsController : BaseController
    {
        public StreetsController(ApplicationDbContext context) : base(context)
        {
             
        }

        // GET: Streets
        public IActionResult Index(int page = 1, string name = "", int cityId = 0, char? letter = null)
        {
            int totalRows;
            int totalPages;
            IQueryable<Street> query = _context.Streets.Include(s => s.City).OrderBy(x => x.Name);

            var isEmployee = User.IsInRole(RoleNames.Employee);
            if (isEmployee)
            {
                cityId = CurrentUser?.City?.Id ?? 0;
            }

            if (cityId > 0)
            {
                query = query.Where(x => x.CityId == cityId);
            }


            if (!string.IsNullOrEmpty(name))
            {
                query = query.Where(x => x.Name.Contains(name));
            }

            if (letter.HasValue)
            {
                query = query.Where(x => x.Name.Length > 1 && Char.ToUpper(x.Name[0]) == Char.ToUpper(letter.Value));
            }


            var dbItems = query.PagedResult(page, 20, x => x.Name, false, out totalRows, out totalPages);
            
            var items = dbItems.ToList().Select(x => StreetItemViewModel.Create(x));

            ViewBag.CurrentPage = page;
            ViewBag.TotalPages = totalPages;
            ViewBag.Letter = letter;


            var model = new SteetMainModel
            {
                Items = items.ToList(),
                Filter = new StreetFilterModel
                {
                    Name = name,
                    CityId = cityId
                }
            };
            return View(model);
        }

        [HttpPost]
        public IActionResult Filter(StreetFilterModel filter, int page = 1)
        {
            return RedirectToAction("Index", new
            {
                page = page,
                name = filter.Name,
                cityId = filter.CityId
            });
        }
        // GET: Streets/Details/5
        public IActionResult Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            Street street = _context.Streets.Single(m => m.Id == id);
            if (street == null)
            {
                return NotFound();
            }

            return View(street);
        }

        // GET: Streets/Create
        public IActionResult Create()
        {
            var model = new StreetItemViewModel()
            {
                 Name = "",
                 CityId = 0
            };
            return View("Save", model);
        }

        // POST: Streets/Create
        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Create(StreetItemViewModel model)
        {
            if (ModelState.IsValid)
            {
                var existingStreet = _context.Streets.FirstOrDefault(x => x.CityId == model.CityId && x.Name.ToLower() == model.Name.ToLower());
                if (existingStreet != null)
                {
                    ErrorMessage("Улица с таким именем уже существует!");
                    model.CityId = model.CityId;
                    return View("Save", model);
                }

                var street = new Street
                {
                    Name = model.Name,
                    CityId = model.CityId
                };
                _context.Streets.Add(street);
                _context.SaveChanges();

                var editUrl = Url.Action("Edit", new { id = street.Id });
                SuccessMessage($"<a href=\"{editUrl}\">Запись</a> была создана");
                return RedirectToAction("Index");
            }
            return View("Save", model);
        }

        // GET: Streets/Edit/5
        public IActionResult Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            Street street = _context.Streets.Include(x => x.City).Single(m => m.Id == id);
            if (street == null)
            {
                return NotFound();
            }
            
            var model = StreetItemViewModel.Create(street);
            return View("Save", model);
        }

        // POST: Streets/Edit/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Edit(StreetItemViewModel model)
        {
            if (ModelState.IsValid)
            {
                Street street = _context.Streets.Include(x => x.City).Single(m => m.Id == model.Id);
                street.Name = model.Name;
                street.CityId = model.CityId;
                _context.Update(street);
                _context.SaveChanges();

                var editUrl = Url.Action("Edit", new { id = model.Id });
                SuccessMessage($"<a href=\"{editUrl}\">Запись</a> была успешно изменена");

                return RedirectToAction("Index");
            }
            
            return View(model);
        }

        // GET: Streets/Delete/5
        [ActionName("Delete")]
        public IActionResult Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            Street street = _context.Streets.Single(m => m.Id == id);
            if (street == null)
            {
                return NotFound();
            }

            _context.Streets.Remove(street);
            _context.SaveChanges();

            SuccessMessage("Запись была удалена");

            return RedirectToAction("Index");
        }
        
        public JsonResult Search(string q)
        {
            var query = _context.Streets.Include(x => x.City).Where(x => x.Name.Contains(q)).ToList();

            return new JsonResult(new
            {
                success = true,
                results = query.Select(x => new SearchResultItem { title= x.Name, description = x.City.Name })
            });
        }
    }
}

Web/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html ng-app="RealEstateMVCApp">
    <head>
        <meta charset="utf-8" />
        <meta name="viewport" content="width=device-width, initial-scale=1.0" />
        <title>@ViewData["Title"] - WebApp</title>

        <environment names="Development">
            <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.css" />
            <link rel="stylesheet" href="~/css/site.css" />
        </environment>
        <environment names="Staging,Production">
            <link rel="stylesheet" href="https://ajax.aspnetcdn.com/ajax/bootstrap/3.3.5/css/bootstrap.min.css"
                  asp-fallback-href="~/lib/bootstrap/dist/css/bootstrap.min.css"
                  asp-fallback-test-class="sr-only" asp-fallback-test-property="position" asp-fallback-test-value="absolute" />
            <link rel="stylesheet" href="~/css/site.min.css" asp-append-version="true" />
        </environment>
    </head>
    <body>
        <div class="navbar navbar-inverse navbar-fixed-top">
            <div class="container">
                <div class="navbar-header">
                    <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                        <span class="sr-only">Toggle navigation</span>
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                    </button>
                    <a asp-controller="Home" asp-action="Index" class="navbar-brand">WebApp</a>
                </div>
                <div class="navbar-collapse collapse">
                    <ul class="nav navbar-nav">
                        <li><a asp-controller="Home" asp-action="Index">Home</a></li>
                        <li><a asp-controller="Home" asp-action="About">About</a></li>
                        <li><a asp-controller="Home" asp-action="Contact">Contact</a></li>
                    </ul>
                    @await Html.PartialAsync("_LoginPartial")
                </div>
            </div>
        </div>
        <div class="container body-content">
            @RenderBody()
            <hr />
            <footer>
                <p>&copy; 2016 - WebApp</p>
            </footer>
        </div>

        <environment names="Development">
            <script src="~/lib/angular/angular.min.js"></script>
           
            <script src="~/controllers/home.controller.js"></script>
            <script src="~/App.js"></script>
            <script src="~/js/site.js" asp-append-version="true"></script>
        </environment>
        <environment names="Staging,Production">
            <script src="https://ajax.aspnetcdn.com/ajax/jquery/jquery-2.1.4.min.js"
                    asp-fallback-src="~/lib/jquery/dist/jquery.min.js"
                    asp-fallback-test="window.jQuery">
            </script>
            <script src="https://ajax.aspnetcdn.com/ajax/bootstrap/3.3.5/bootstrap.min.js"
                    asp-fallback-src="~/lib/bootstrap/dist/js/bootstrap.min.js"
                    asp-fallback-test="window.jQuery && window.jQuery.fn && window.jQuery.fn.modal">
            </script>
            <script src="~/js/site.min.js" asp-append-version="true"></script>
        </environment>

        @RenderSection("scripts", required: false)
    </body>
</html>

Web/Views/Shared/_LayoutSemanticUI.cshtml
<!DOCTYPE html>
<html ng-app="RealEstateMVCApp">
    <head>
        <meta charset="utf-8" />
        <meta name="viewport" content="width=device-width, initial-scale=1.0" />
        <title>@ViewData["Title"] - WebApp</title>

        <environment names="Development">
            <link rel="stylesheet" href="~/css/site.css"/>
            <link rel="stylesheet" href="~/lib/semantic/dist/semantic.css"/>
            <link rel="stylesheet" type="text/css" href="~/lib/semantic/dist/components/reset.css">
            <link rel="stylesheet" type="text/css" href="~/lib/semantic/dist/components/site.css">
            <link rel="stylesheet" type="text/css" href="~/lib/semantic/dist/components/container.css">
            <link rel="stylesheet" type="text/css" href="~/lib/semantic/dist/components/grid.css">
            <link rel="stylesheet" type="text/css" href="~/lib/semantic/dist/components/header.css">
            <link rel="stylesheet" type="text/css" href="~/lib/semantic/dist/components/image.css">
            <link rel="stylesheet" type="text/css" href="~/lib/semantic/dist/components/menu.css">
            <link rel="stylesheet" type="text/css" href="~/lib/semantic/dist/components/divider.css">
            <link rel="stylesheet" type="text/css" href="~/lib/semantic/dist/components/dropdown.css">
            <link rel="stylesheet" type="text/css" href="~/lib/semantic/dist/components/segment.css">
            <link rel="stylesheet" type="text/css" href="~/lib/semantic/dist/components/button.css">
            <link rel="stylesheet" type="text/css" href="~/lib/semantic/dist/components/list.css">
            <link rel="stylesheet" type="text/css" href="~/lib/semantic/dist/components/icon.css">
            <link rel="stylesheet" type="text/css" href="~/lib/semantic/dist/components/sidebar.css">
            <link rel="stylesheet" type="text/css" href="~/lib/semantic/dist/components/transition.css">
            <link rel="stylesheet" type="text/css" href="~/lib/jquery-ui/themes/base/jquery-ui.css">


            <link href="~/lib/pnotify/dist/pnotify.css" media="all" rel="stylesheet" type="text/css"/>
            <link href="~/lib/pnotify/dist/pnotify.brighttheme.css" media="all" rel="stylesheet" type="text/css"/>
            <style>
                .main.container {
                    margin-top: 4em;
                }
            </style>
            <script src="https://ajax.aspnetcdn.com/ajax/jquery/jquery-2.1.4.min.js"
                    asp-fallback-src="~/lib/jquery/dist/jquery.min.js"
                    asp-fallback-test="window.jQuery">

            
            </script>

            <script src="~/lib/jquery-validation/dist/jquery.validate.js"></script>
            <script src="~/lib/jquery-validation-unobtrusive/jquery.validate.unobtrusive.js"></script>

            <script src="~/lib/jquery-ui/jquery-ui.js"></script>
            <script src="~/lib/notifyjs/dist/notify.js"></script>
            <script src="~/lib/pnotify/dist/pnotify.js"></script>
            <script src="~/lib/semantic/dist/semantic.js"></script>
            <script src="~/Scripts/Utils.js"></script>
        </environment>
    </head>
    <body>
    <div class="ui fixed menu" id="topMenu">
        <div class="ui container">
            <a asp-controller="Home" asp-action="Index" class="header item">
                RealEstate CRM
            </a>
            <a class="item" asp-controller="Employee" asp-action="Index">Сотрудники</a>
            <a class="item" asp-controller="Housing" asp-action="Index">Объекты</a>
            <a class="item" asp-controller="BlackList" asp-action="Index">Черный список</a>
            <a class="item" asp-controller="Streets" asp-action="Index">Список улиц</a>
            <a class="item" asp-controller="Customers" asp-action="Index">Клиенты</a>
            <div class="ui simple dropdown item">
                Админка <i class="dropdown icon"></i>
                <div class="menu right">
                    <a class="item" asp-controller="Employee" asp-action="Index">Сотрудники</a>
                    <a class="item" asp-controller="Housing" asp-action="Index">Объекты</a>
                    <a class="item" asp-controller="BlackList" asp-action="Index">Черный список</a>
                    <a class="item" asp-controller="Streets" asp-action="Index">Список улиц</a>
                    <a class="item" asp-controller="Customers" asp-action="Index">Клиенты</a>
                </div>
            </div>
            <div class="menu right">                
                @await Html.PartialAsync("_LoginPartialSemanticUI")
            </div>
             <div class="menu" id="notifyBlock">
                
            </div>
        </div>
    </div>
    
        <!-- Page Contents -->
    <div class="ui main container" ng-view="">
        @if (TempData["CrmSuccessMessage"] != null)
        {
            <div class="ui success message">
                <i class="close icon"></i>
                <div class="header">@Html.Raw(TempData["CrmSuccessMessage"].ToString())</div>
                <!--<p>You may now log-in with the username you have chosen</p>-->
            </div>
        }
        @if (TempData["CrmErrorMessage"] != null)
        {
            <div class="ui negative message">
                <i class="close icon"></i>
                <div class="header">@Html.Raw(TempData["CrmErrorMessage"].ToString())</div>
                <!--<p>You may now log-in with the username you have chosen</p>-->
            </div>
        }

        @if (ViewBag.SectionTitle != null)
        {
            <h2 class="ui dividing header">@ViewBag.SectionTitle</h2>
        }
        @RenderBody()
    </div>
        <!--
        <div class="ui inverted vertical footer segment">
            <div class="ui container">
                <div class="ui stackable inverted divided equal height stackable grid">
                    <div class="three wide column">
                        <h4 class="ui inverted header">About</h4>
                        <div class="ui inverted link list">
                            <a href="#" class="item">Sitemap</a>
                            <a href="#" class="item">Contact Us</a>
                            <a href="#" class="item">Religious Ceremonies</a>
                            <a href="#" class="item">Gazebo Plans</a>
                        </div>
                    </div>
                    <div class="three wide column">
                        <h4 class="ui inverted header">Services</h4>
                        <div class="ui inverted link list">
                            <a href="#" class="item">Banana Pre-Order</a>
                            <a href="#" class="item">DNA FAQ</a>
                            <a href="#" class="item">How To Access</a>
                            <a href="#" class="item">Favorite X-Men</a>
                        </div>
                    </div>
                    <div class="seven wide column">
                        <h4 class="ui inverted header">Footer Header</h4>
                        <p>Extra space for a call to action inside the footer that could help re-engage users.</p>
                    </div>
                </div>
            </div>
        </div>-->
            

            <environment names="Development">

                <script>
                    $('.ui.dropdown').not('.ui-ignore').dropdown();
                    $('.ui.checkbox').not('.ui-ignore').checkbox();

                    $(document).ready(function () {
                        $(".selectDateInput").datepicker({
                            "dateFormat": "dd.mm.yy",
                            changeMonth: true
                        });

                      /*  $("form").submit(function(event) {
                            //$('.input-validation-error').parents('div.field').eq(0).addClass('ui input error');
                            //$('.field-validation-error').addClass('ui label pointing red');

                            //$('.field-validation-valid').removeClass('ui label  pointing red');
                        });*/
                    });
                </script>
            </environment>

            @RenderSection("scripts", required: false)
            @RenderSection("editscripts", required: false)
</body>
</html>

Web/Views/Shared/_LoginPartialSemanticUI.cshtml
@using System.Security.Claims

@{ 
    var customer = CustomerUser.FromSession(Context.Session);
}
@if (User.Identity.IsAuthenticated)
{
      <form asp-controller="Account" asp-action="LogOff" method="post" id="logoutForm" class="">
          <a asp-controller="Manage" asp-action="Index" title="Manage">Привет @User.Identity.Name!</a>
          <button type="submit" class="ui button blue inverted"><i class="sign out icon"></i>Выйти</button>
      </form>
}
else if (customer != null) { 
    <form asp-controller="Account" asp-action="CustomerLogOff" method="post" id="logoutCustomerForm" class="">     
        <span>Привет @customer.CustomerName</span>     
         <button type="submit" class="ui button blue inverted"><i class="sign out icon"></i>Выйти</button>
     </form>
}
else
{
    @*<a asp-controller="Account" asp-action="Register">Регистрация</a>
    <a asp-controller="Account" asp-action="Login">Войти</a>*@

    <div class="ui simple dropdown item">
        Войти как  <i class="dropdown icon"></i>
        <div class="menu right">                    
            <a class="item" asp-controller="Account" asp-action="Login">Сотрудник</a>
            <a class="item" asp-controller="Account" asp-action="CustomerLogin">Клиент</a>
        </div>
    </div>
}